### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by lyd0527** [refresh-bio/GTShark#1]
Hi,

I have compiled GTShark successfully on the server with CentOS7, gcc. But I got "Illegal instruction (core dumped)" when I performed the command `gtshark compress-db raw.vcf.gz output.gts`.

Thanks,

Yuanda

**Comment by agnieszkadanek** [comment]
Could you please provide an example input VCF file to reproduce the error?

**Comment by lyd0527** [comment]
I can't use GTShark to compress any VCF file. The compiling process is normal, but the running is crashed. Is there any hidden dependency program? Now I have installed gcc 4.9 and clang 3.2.

Fortunately, GTC is running well now. Thank you~

**Comment by agnieszkadanek** [comment]
I added two Dockerfiles (Dockerfile_ubuntu and Dockerfile_centos) and a corresponding Dockerfile section in the README. 

The second image is based on CentOS7 and contain all necessary dependencies for GTShark. GTShark compiles and runs correctly within the created Docker container (toy example can be used for tests). Please take a look.

**Comment by agnieszkadanek** [comment]
As for your case: 
Is it possible that you have a processor ***without*** AVX support?
Possibly, your compiler can produce AVX code, but your processor does not support it.

If that is the case, remove ```-mavx``` flag from makefile (instead, add  ```-msse4.2``` flag, for example).

Please let me know if that solves your problem.

**Comment by agnieszkadanek** [comment]
I’m closing this issue because it has been inactive for a few months. I assume that my comments helped you resolved your issue. 

Please reopen if you still encounter this issue.
