### ISSUE TITLE
complie

### ISSUE THREAD

**Issue by SmDonkey** [refresh-bio/GTShark#2]
Hi,
i got a error when i complie the gtshark.i use the Ubuntu 16.04.4

-lm -O3 -std=c++11 -pthread -mavx -lz -lbz2 -lcurl  -llzma  -L .  -fabi-version=6
/usr/bin/ld: htslib/lib/libhts.a(hfile_s3.o): undefined reference to symbol 'EVP_sha1@@OPENSSL_1.0.0'
//lib/x86_64-linux-gnu/libcrypto.so.1.0.0: error adding symbols: DSO missing from command line

do u know how to solve the problem?

thanks a lot!

**Comment by agnieszkadanek** [comment]
Hi,

It looks like some HTSlib library linking problems.  Try adding ```-lcrypto``` to CLINK in the makefile. 

Nevertheless, GTShark should compile for Ubuntu 16.04 without ```-lcrypto``` flag. Do you have all packages listed in ```Dockerfile_ubuntu``` installed (see Dockerfile section in the README for details)? The Dockerfile here is for Ubuntu 18.04, but I locally changed it to 16.04 and deleted last line. Then, after adding ```lzma12.h``` header file to ```/usr/include/lzma``` in the running container (as apparently it is missing), compilation works.

**Comment by SmDonkey** [comment]
hi,
It‘'s fine! Thanks u very much! I also tried to add -libcrypto to the CLINK but it clearly failed.
What's more, have you ever considered permute the order of the rows? I think that should improve the PBWT, right?

**Comment by agnieszkadanek** [comment]
What solved your issue? Was it adding ```-lcrypto``` flag?

We have not considered permuting the order of the rows.

**Comment by SmDonkey** [comment]
Yes, adding -lcrypto solved my compilation problem.

These days I tried to permute the order of the rows(server clustering methods)and then used the GTshark to compress the file. Because I think put similar lines together can impove the PWBT( as I understand it, the more similar adjacent lines are, the better the PBWT arrangement works ). Unfortunately, it didn't turn out the way I expected. 

Thanks for your answer!
